export const WORKOUT_PLAN = {
  monday: {
    id: 'monday',
    type: 'Push A',
    label: 'Segunda-feira',
    focus: 'Peito',
    color: '#C8FF00',
    emoji: '💪',
    exercises: [
      {
        id: 'ex_push_a_01',
        name: 'Supino Reto com Barra',
        muscles: ['Peito', 'Tríceps', 'Ombro'],
        primaryMuscle: 'Peito',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Bench press',
        description: 'Deite no banco, segure a barra com pegada maior que a largura dos ombros. Desça até o peito controlando, empurre explosivamente para cima. Mantenha os cotovelos em 45–75°.',
        tips: ['Retrate as escápulas antes de começar', 'Pés firmes no chão', 'Barra em linha com o baixo peito'],
      },
      {
        id: 'ex_push_a_02',
        name: 'Supino Inclinado com Halteres',
        muscles: ['Peito Superior', 'Ombro', 'Tríceps'],
        primaryMuscle: 'Peito Superior',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Incline Dumbbell Bench Press',
        description: 'Banco a 30–45°. Segure os halteres alinhados com o peito superior. Desça controlando e empurre até a extensão quase completa.',
        tips: ['Não deixe os cotovelos caírem abaixo do banco', 'Foco na contração no topo'],
      },
      {
        id: 'ex_push_a_03',
        name: 'Crucifixo com Cabos',
        muscles: ['Peito', 'Ombro Anterior'],
        primaryMuscle: 'Peito',
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Cable Crossover',
        description: 'Polias na altura do ombro. Avance um pé, traga os cabos em arco à frente do peito. Sinta a contração no centro.',
        tips: ['Leve flexão nos cotovelos durante todo o movimento', 'Controle a fase excêntrica'],
      },
      {
        id: 'ex_push_a_04',
        name: 'Desenvolvimento com Halteres',
        muscles: ['Ombro', 'Tríceps'],
        primaryMuscle: 'Ombro',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Dumbbell Shoulder Press',
        description: 'Sentado ou em pé com halteres na altura dos ombros. Empurre acima da cabeça sem bloquear os cotovelos no topo.',
        tips: ['Núcleo ativo para proteger a lombar', 'Não arqueie excessivamente as costas'],
      },
      {
        id: 'ex_push_a_05',
        name: 'Elevação Lateral',
        muscles: ['Ombro Lateral'],
        primaryMuscle: 'Ombro Lateral',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Lateral raise',
        description: 'Em pé, halteres ao lado do corpo. Eleve lateralmente até a altura dos ombros com leve inclinação para frente. Controle a descida.',
        tips: ['Polegares levemente para baixo no topo', 'Evite usar impulso do tronco'],
      },
      {
        id: 'ex_push_a_06',
        name: 'Tríceps Corda (Pulley)',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Triceps pushdown',
        description: 'Polia alta com corda. Cotovelos fixos ao lado do corpo. Puxe a corda para baixo abrindo as pontas ao final da extensão.',
        tips: ['Cotovelos fixos, não os deixe abrir', 'Contração total no fundo do movimento'],
      },
    ],
  },
  tuesday: {
    id: 'tuesday',
    type: 'Pull A',
    label: 'Terça-feira',
    focus: 'Costas',
    color: '#818CF8',
    emoji: '🔥',
    exercises: [
      {
        id: 'ex_pull_a_01',
        name: 'Barra Fixa (Pull-up)',
        muscles: ['Latíssimo', 'Bíceps', 'Rombóide'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Pull-up',
        description: 'Pegada pronada um pouco mais larga que os ombros. Puxe até o queixo acima da barra. Desça completamente controlando.',
        tips: ['Inicie o movimento deprimindo as escápulas', 'Evite balançar o corpo'],
      },
      {
        id: 'ex_pull_a_02',
        name: 'Remada Curvada com Barra',
        muscles: ['Costas Média', 'Latíssimo', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Barbell Row',
        description: 'Tronco a 45° com a barra. Puxe para o umbigo retraindo as escápulas. Cotovelos próximos ao corpo.',
        tips: ['Joelhos levemente flexionados', 'Não arredonde a lombar'],
      },
      {
        id: 'ex_pull_a_03',
        name: 'Pulldown na Polia',
        muscles: ['Latíssimo', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lat pulldown',
        description: 'Pegada pronada larga. Incline o tronco ligeiramente para trás e puxe a barra até o queixo. Controle a subida.',
        tips: ['Puxe com os cotovelos, não com as mãos', 'Abra o peito na contração'],
      },
      {
        id: 'ex_pull_a_04',
        name: 'Rosca Direta com Barra',
        muscles: ['Bíceps', 'Braquial'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Barbell curl',
        description: 'Em pé, pegada supinada na barra. Flexione os cotovelos subindo até os ombros. Controle a descida.',
        tips: ['Cotovelos fixos ao lado do corpo', 'Não use o balanço do tronco'],
      },
      {
        id: 'ex_pull_a_05',
        name: 'Rosca Martelo',
        muscles: ['Bíceps', 'Braquiorradial'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Hammer curl',
        description: 'Pegada neutra com halteres. Flexione alternado ou simultaneamente até os ombros. Excelente para o braquiorradial.',
        tips: ['Polegares sempre apontando para cima', 'Movimento lento na descida'],
      },
      {
        id: 'ex_pull_a_06',
        name: 'Encolhimento com Barra',
        muscles: ['Trapézio'],
        primaryMuscle: 'Trapézio',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Barbell shrug',
        description: 'Em pé com a barra na frente. Eleve os ombros em direção às orelhas sem rodar. Segure 1s no topo.',
        tips: ['Não role os ombros', 'Mantenha os braços estendidos'],
      },
    ],
  },
  wednesday: {
    id: 'wednesday',
    type: 'Legs A',
    label: 'Quarta-feira',
    focus: 'Quadríceps',
    color: '#F59E0B',
    emoji: '🦵',
    exercises: [
      {
        id: 'ex_legs_a_01',
        name: 'Agachamento Livre',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Quadríceps',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 120,
        wgerName: 'Squat',
        description: 'Barra nos trapézios, pés na largura dos ombros. Desça com o quadril para trás e abaixo até as coxas paralelas. Empurre o chão na subida.',
        tips: ['Joelhos seguem a direção dos pés', 'Peito alto durante todo o movimento', 'Respire fundo antes de cada rep'],
      },
      {
        id: 'ex_legs_a_02',
        name: 'Leg Press 45°',
        muscles: ['Quadríceps', 'Glúteos'],
        primaryMuscle: 'Quadríceps',
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 75,
        wgerName: 'Leg press',
        description: 'Pés na largura dos ombros na plataforma. Desça controlando até 90° e empurre sem travar os joelhos no topo.',
        tips: ['Não deixe os glúteos saírem do banco', 'Posição alta dos pés recruta mais glúteo'],
      },
      {
        id: 'ex_legs_a_03',
        name: 'Cadeira Extensora',
        muscles: ['Quadríceps'],
        primaryMuscle: 'Quadríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Leg extension',
        description: 'Sentado na cadeira extensora. Estenda completamente os joelhos e controle a fase excêntrica.',
        tips: ['Pause 1s na extensão completa', 'Não use peso excessivo — foco na contração'],
      },
      {
        id: 'ex_legs_a_04',
        name: 'Avanço com Halteres',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Glúteos',
        sets: 3,
        repsMin: 10,
        repsMax: 10,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lunge',
        description: 'Em pé com halteres. Avance um passo largo. O joelho traseiro quase toca o chão. Empurre de volta à posição inicial.',
        tips: ['Tronco ereto', 'O joelho da frente não ultrapassa a ponta do pé'],
      },
      {
        id: 'ex_legs_a_05',
        name: 'Panturrilha em Pé na Máquina',
        muscles: ['Panturrilha', 'Sóleo'],
        primaryMuscle: 'Panturrilha',
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Standing calf raise',
        description: 'Na máquina de panturrilha em pé. Eleve completamente na ponta dos pés, segure 1s, desça abaixo da plataforma.',
        tips: ['Amplitude completa para máximo recrutamento', 'Não use impulso'],
      },
      {
        id: 'ex_legs_a_06',
        name: 'Abdominais',
        muscles: ['Abdômen'],
        primaryMuscle: 'Core',
        sets: 3,
        repsMin: 20,
        repsMax: 20,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Crunch',
        description: 'Deitado com joelhos flexionados. Eleve o tronco contraindo o abdômen. Não puxe a cabeça com as mãos.',
        tips: ['Respire na subida', 'Mantenha o lombar em contato com o chão'],
      },
    ],
  },
  thursday: {
    id: 'thursday',
    type: 'Push B',
    label: 'Quinta-feira',
    focus: 'Ombro',
    color: '#EC4899',
    emoji: '⚡',
    exercises: [
      {
        id: 'ex_push_b_01',
        name: 'Desenvolvimento com Barra (Militar Press)',
        muscles: ['Ombro', 'Tríceps', 'Trapézio'],
        primaryMuscle: 'Ombro',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Military Press',
        description: 'Em pé ou sentado com a barra na altura dos ombros. Empurre verticalmente até a extensão quase completa. Controle a descida.',
        tips: ['Glúteos e abdômen contraídos para estabilidade', 'Cotovelos ligeiramente à frente'],
      },
      {
        id: 'ex_push_b_02',
        name: 'Elevação Lateral com Halteres',
        muscles: ['Ombro Lateral'],
        primaryMuscle: 'Ombro Lateral',
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lateral raise',
        description: 'Halteres ao lado do corpo. Eleve lateralmente com leve inclinação para frente até a linha dos ombros.',
        tips: ['Cotovelos levemente flexionados', 'Imagine derramar água de um balde'],
      },
      {
        id: 'ex_push_b_03',
        name: 'Elevação Frontal',
        muscles: ['Ombro Anterior'],
        primaryMuscle: 'Ombro Anterior',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Front raise',
        description: 'Com halteres ou barra, eleve para a frente até a altura dos ombros. Controle a descida.',
        tips: ['Não incline o tronco para trás', 'Movimento lento e controlado'],
      },
      {
        id: 'ex_push_b_04',
        name: 'Supino Inclinado com Barra',
        muscles: ['Peito Superior', 'Ombro', 'Tríceps'],
        primaryMuscle: 'Peito Superior',
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        intensity: 'Hipertrofia',
        restSeconds: 75,
        wgerName: 'Incline Bench Press',
        description: 'Banco a 30–45°. Barra desce até o peito superior. Empurre explosivamente e controle a descida.',
        tips: ['Espaldar bem posicionado antes do levantamento', 'Pegada na largura dos ombros'],
      },
      {
        id: 'ex_push_b_05',
        name: 'Mergulho nas Paralelas',
        muscles: ['Tríceps', 'Peito', 'Ombro'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Dips',
        description: 'Nas barras paralelas. Desça até os braços formarem 90° ou mais. Tronco levemente inclinado para frente recruta mais peito.',
        tips: ['Controle total na fase excêntrica', 'Evite postura muito ereta se quiser foco no tríceps'],
      },
      {
        id: 'ex_push_b_06',
        name: 'Tríceps Francês',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Skull crusher',
        description: 'Deitado com barra EZ ou halteres. Desça flexionando os cotovelos até a testa. Estenda completamente.',
        tips: ['Cotovelos apontados para o teto', 'Amplitude completa para máximo alongamento'],
      },
    ],
  },
  friday: {
    id: 'friday',
    type: 'Pull B',
    label: 'Sexta-feira',
    focus: 'Costas 2',
    color: '#14B8A6',
    emoji: '🎯',
    exercises: [
      {
        id: 'ex_pull_b_01',
        name: 'Remada Unilateral com Halter',
        muscles: ['Latíssimo', 'Rombóide', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 10,
        repsMax: 10,
        intensity: 'Força',
        restSeconds: 75,
        wgerName: 'One arm dumbbell row',
        description: 'Apoie um joelho e mão no banco. Puxe o halter em direção ao quadril retraindo a escápula. Controle a descida completa.',
        tips: ['Não rotacione o tronco durante a puxada', 'Cotovelada para trás e para cima'],
      },
      {
        id: 'ex_pull_b_02',
        name: 'Remada Baixa na Polia',
        muscles: ['Costas Média', 'Bíceps', 'Rombóide'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Seated row',
        description: 'Sentado na polia baixa. Puxe a pegada até o abdômen retraindo as escápulas. Não arredonde as costas.',
        tips: ['Tronco ereto durante todo o movimento', 'Cotovelos passam pelo lado do corpo'],
      },
      {
        id: 'ex_pull_b_03',
        name: 'Puxada Aberta na Polia',
        muscles: ['Latíssimo', 'Redondo Maior'],
        primaryMuscle: 'Costas',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Wide-grip lat pulldown',
        description: 'Pegada pronada bem aberta. Puxe até o queixo com os cotovelos apontando para o chão.',
        tips: ['Abra o peito na contração', 'Não incline excessivamente para trás'],
      },
      {
        id: 'ex_pull_b_04',
        name: 'Rosca Concentrada',
        muscles: ['Bíceps'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Concentration curl',
        description: 'Sentado com o cotovelo apoiado na parte interna da coxa. Flexione completamente até a contração máxima.',
        tips: ['Movimento lento e deliberado', 'Squeeze no topo por 1 segundo'],
      },
      {
        id: 'ex_pull_b_05',
        name: 'Rosca 21',
        muscles: ['Bíceps'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 21,
        repsMax: 21,
        intensity: 'Resistência',
        restSeconds: 75,
        wgerName: 'Barbell curl',
        description: '7 reps da parte baixa (0° a 90°), 7 da parte alta (90° a 180°), 7 completas. Sensação de queimação total!',
        tips: ['Use carga moderada — a técnica é exigente', 'Foco na contração em cada faixa'],
      },
      {
        id: 'ex_pull_b_06',
        name: 'Encolhimento com Halteres',
        muscles: ['Trapézio'],
        primaryMuscle: 'Trapézio',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Dumbbell shrug',
        description: 'Em pé com halteres ao lado do corpo. Eleve os ombros em direção às orelhas. Segure 2s no topo.',
        tips: ['Amplitude total — desça completamente', 'Não role os ombros para frente'],
      },
    ],
  },
  saturday: { id: 'saturday', type: 'Rest', label: 'Sábado', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
  sunday: { id: 'sunday', type: 'Rest', label: 'Domingo', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
}

export const DAY_ORDER = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

export const DAY_LABELS_SHORT = {
  monday: 'Seg',
  tuesday: 'Ter',
  wednesday: 'Qua',
  thursday: 'Qui',
  friday: 'Sex',
  saturday: 'Sáb',
  sunday: 'Dom',
}

export function getTodayKey() {
  const days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
  return days[new Date().getDay()]
}

export function getIntensityColor(intensity) {
  switch (intensity) {
    case 'Força': return '#EF4444'
    case 'Hipertrofia': return '#C8FF00'
    case 'Resistência': return '#F59E0B'
    default: return '#888'
  }
}

export function formatReps(min, max) {
  if (min === max) return `${min}`
  return `${min}–${max}`
}
