export const WORKOUT_PLAN = {
  monday: {
    id: 'monday',
    type: 'Push A',
    label: 'Segunda-feira',
    focus: 'Peito',
    color: '#C8FF00',
    emoji: '💪',
    exercises: [
      {
        id: 'ex_push_a_01',
        wgerId: 192,
        name: 'Supino Reto com Barra',
        muscles: ['Peito', 'Tríceps', 'Ombro'],
        primaryMuscle: 'Peito',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Bench press',
        description: 'Deite no banco, segure a barra com pegada maior que a largura dos ombros. Desça até o peito controlando, empurre explosivamente para cima. Mantenha os cotovelos em 45–75°.',
        tips: ['Retrate as escápulas antes de começar', 'Pés firmes no chão', 'Barra em linha com o baixo peito'],
      },
      {
        id: 'ex_push_a_02',
        name: 'Supino Inclinado com Halteres',
        muscles: ['Peito Superior', 'Ombro', 'Tríceps'],
        primaryMuscle: 'Peito Superior',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Incline Dumbbell Bench Press',
        description: 'Banco a 30–45°. Segure os halteres alinhados com o peito superior. Desça controlando e empurre até a extensão quase completa.',
        tips: ['Não deixe os cotovelos caírem abaixo do banco', 'Foco na contração no topo'],
      },
      {
        id: 'ex_push_a_03',
        name: 'Crucifixo com Cabos',
        muscles: ['Peito', 'Ombro Anterior'],
        primaryMuscle: 'Peito',
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Cable Crossover',
        description: 'Polias na altura do ombro. Avance um pé, traga os cabos em arco à frente do peito. Sinta a contração no centro.',
        tips: ['Leve flexão nos cotovelos durante todo o movimento', 'Controle a fase excêntrica'],
      },
      {
        id: 'ex_push_a_04',
        wgerId: 72,
        name: 'Desenvolvimento com Halteres',
        muscles: ['Ombro', 'Tríceps'],
        primaryMuscle: 'Ombro',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Dumbbell Shoulder Press',
        description: 'Sentado ou em pé com halteres na altura dos ombros. Empurre acima da cabeça sem bloquear os cotovelos no topo.',
        tips: ['Núcleo ativo para proteger a lombar', 'Não arqueie excessivamente as costas'],
      },
      {
        id: 'ex_push_a_05',
        wgerId: 112,
        name: 'Elevação Lateral',
        muscles: ['Ombro Lateral'],
        primaryMuscle: 'Ombro Lateral',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Lateral raise',
        description: 'Em pé, halteres ao lado do corpo. Eleve lateralmente até a altura dos ombros com leve inclinação para frente. Controle a descida.',
        tips: ['Polegares levemente para baixo no topo', 'Evite usar impulso do tronco'],
      },
      {
        id: 'ex_push_a_06',
        wgerId: 63,
        name: 'Tríceps Corda (Pulley)',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Triceps pushdown',
        description: 'Polia alta com corda. Cotovelos fixos ao lado do corpo. Puxe a corda para baixo abrindo as pontas ao final da extensão.',
        tips: ['Cotovelos fixos, não os deixe abrir', 'Contração total no fundo do movimento'],
      },
    ],
  },
  tuesday: {
    id: 'tuesday',
    type: 'Pull A',
    label: 'Terça-feira',
    focus: 'Costas',
    color: '#818CF8',
    emoji: '🔥',
    exercises: [
      {
        id: 'ex_pull_a_01',
        wgerId: 31,
        name: 'Barra Fixa (Pull-up)',
        muscles: ['Latíssimo', 'Bíceps', 'Rombóide'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Pull-up',
        description: 'Pegada pronada um pouco mais larga que os ombros. Puxe até o queixo acima da barra. Desça completamente controlando.',
        tips: ['Inicie o movimento deprimindo as escápulas', 'Evite balançar o corpo'],
      },
      {
        id: 'ex_pull_a_02',
        name: 'Remada Curvada com Barra',
        muscles: ['Costas Média', 'Latíssimo', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Barbell Row',
        description: 'Tronco a 45° com a barra. Puxe para o umbigo retraindo as escápulas. Cotovelos próximos ao corpo.',
        tips: ['Joelhos levemente flexionados', 'Não arredonde a lombar'],
      },
      {
        id: 'ex_pull_a_03',
        wgerId: 102,
        name: 'Pulldown na Polia',
        muscles: ['Latíssimo', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lat pulldown',
        description: 'Pegada pronada larga. Incline o tronco ligeiramente para trás e puxe a barra até o queixo. Controle a subida.',
        tips: ['Puxe com os cotovelos, não com as mãos', 'Abra o peito na contração'],
      },
      {
        id: 'ex_pull_a_04',
        wgerId: 84,
        name: 'Rosca Direta com Barra',
        muscles: ['Bíceps', 'Braquial'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Barbell curl',
        description: 'Em pé, pegada supinada na barra. Flexione os cotovelos subindo até os ombros. Controle a descida.',
        tips: ['Cotovelos fixos ao lado do corpo', 'Não use o balanço do tronco'],
      },
      {
        id: 'ex_pull_a_05',
        wgerId: 118,
        name: 'Rosca Martelo',
        muscles: ['Bíceps', 'Braquiorradial'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Hammer curl',
        description: 'Pegada neutra com halteres. Flexione alternado ou simultaneamente até os ombros. Excelente para o braquiorradial.',
        tips: ['Polegares sempre apontando para cima', 'Movimento lento na descida'],
      },
      {
        id: 'ex_pull_a_06',
        wgerId: 179,
        name: 'Encolhimento com Barra',
        muscles: ['Trapézio'],
        primaryMuscle: 'Trapézio',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Barbell shrug',
        description: 'Em pé com a barra na frente. Eleve os ombros em direção às orelhas sem rodar. Segure 1s no topo.',
        tips: ['Não role os ombros', 'Mantenha os braços estendidos'],
      },
    ],
  },
  wednesday: {
    id: 'wednesday',
    type: 'Legs A',
    label: 'Quarta-feira',
    focus: 'Quadríceps',
    color: '#F59E0B',
    emoji: '🦵',
    exercises: [
      {
        id: 'ex_legs_a_01',
        wgerId: 8,
        name: 'Agachamento Livre',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Quadríceps',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 120,
        wgerName: 'Squat',
        description: 'Barra nos trapézios, pés na largura dos ombros. Desça com o quadril para trás e abaixo até as coxas paralelas. Empurre o chão na subida.',
        tips: ['Joelhos seguem a direção dos pés', 'Peito alto durante todo o movimento', 'Respire fundo antes de cada rep'],
      },
      {
        id: 'ex_legs_a_02',
        wgerId: 45,
        name: 'Leg Press 45°',
        muscles: ['Quadríceps', 'Glúteos'],
        primaryMuscle: 'Quadríceps',
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 75,
        wgerName: 'Leg press',
        description: 'Pés na largura dos ombros na plataforma. Desça controlando até 90° e empurre sem travar os joelhos no topo.',
        tips: ['Não deixe os glúteos saírem do banco', 'Posição alta dos pés recruta mais glúteo'],
      },
      {
        id: 'ex_legs_a_03',
        name: 'Cadeira Extensora',
        muscles: ['Quadríceps'],
        primaryMuscle: 'Quadríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Leg extension',
        description: 'Sentado na cadeira extensora. Estenda completamente os joelhos e controle a fase excêntrica.',
        tips: ['Pause 1s na extensão completa', 'Não use peso excessivo — foco na contração'],
      },
      {
        id: 'ex_legs_a_04',
        wgerId: 80,
        name: 'Avanço com Halteres',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Glúteos',
        sets: 3,
        repsMin: 10,
        repsMax: 10,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lunge',
        description: 'Em pé com halteres. Avance um passo largo. O joelho traseiro quase toca o chão. Empurre de volta à posição inicial.',
        tips: ['Tronco ereto', 'O joelho da frente não ultrapassa a ponta do pé'],
      },
      {
        id: 'ex_legs_a_05',
        name: 'Panturrilha em Pé na Máquina',
        muscles: ['Panturrilha', 'Sóleo'],
        primaryMuscle: 'Panturrilha',
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Standing calf raise',
        description: 'Na máquina de panturrilha em pé. Eleve completamente na ponta dos pés, segure 1s, desça abaixo da plataforma.',
        tips: ['Amplitude completa para máximo recrutamento', 'Não use impulso'],
      },
      {
        id: 'ex_legs_a_06',
        wgerId: 10,
        name: 'Abdominais',
        muscles: ['Abdômen'],
        primaryMuscle: 'Core',
        sets: 3,
        repsMin: 20,
        repsMax: 20,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Crunch',
        description: 'Deitado com joelhos flexionados. Eleve o tronco contraindo o abdômen. Não puxe a cabeça com as mãos.',
        tips: ['Respire na subida', 'Mantenha o lombar em contato com o chão'],
      },
    ],
  },
  thursday: {
    id: 'thursday',
    type: 'Push B',
    label: 'Quinta-feira',
    focus: 'Ombro',
    color: '#EC4899',
    emoji: '⚡',
    exercises: [
      {
        id: 'ex_push_b_01',
        wgerId: 70,
        name: 'Desenvolvimento com Barra (Militar Press)',
        muscles: ['Ombro', 'Tríceps', 'Trapézio'],
        primaryMuscle: 'Ombro',
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        intensity: 'Força',
        restSeconds: 90,
        wgerName: 'Military Press',
        description: 'Em pé ou sentado com a barra na altura dos ombros. Empurre verticalmente até a extensão quase completa. Controle a descida.',
        tips: ['Glúteos e abdômen contraídos para estabilidade', 'Cotovelos ligeiramente à frente'],
      },
      {
        id: 'ex_push_b_02',
        wgerId: 112,
        name: 'Elevação Lateral com Halteres',
        muscles: ['Ombro Lateral'],
        primaryMuscle: 'Ombro Lateral',
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Lateral raise',
        description: 'Halteres ao lado do corpo. Eleve lateralmente com leve inclinação para frente até a linha dos ombros.',
        tips: ['Cotovelos levemente flexionados', 'Imagine derramar água de um balde'],
      },
      {
        id: 'ex_push_b_03',
        name: 'Elevação Frontal',
        muscles: ['Ombro Anterior'],
        primaryMuscle: 'Ombro Anterior',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Front raise',
        description: 'Com halteres ou barra, eleve para a frente até a altura dos ombros. Controle a descida.',
        tips: ['Não incline o tronco para trás', 'Movimento lento e controlado'],
      },
      {
        id: 'ex_push_b_04',
        name: 'Supino Inclinado com Barra',
        muscles: ['Peito Superior', 'Ombro', 'Tríceps'],
        primaryMuscle: 'Peito Superior',
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        intensity: 'Hipertrofia',
        restSeconds: 75,
        wgerName: 'Incline Bench Press',
        description: 'Banco a 30–45°. Barra desce até o peito superior. Empurre explosivamente e controle a descida.',
        tips: ['Espaldar bem posicionado antes do levantamento', 'Pegada na largura dos ombros'],
      },
      {
        id: 'ex_push_b_05',
        wgerId: 37,
        name: 'Mergulho nas Paralelas',
        muscles: ['Tríceps', 'Peito', 'Ombro'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Dips',
        description: 'Nas barras paralelas. Desça até os braços formarem 90° ou mais. Tronco levemente inclinado para frente recruta mais peito.',
        tips: ['Controle total na fase excêntrica', 'Evite postura muito ereta se quiser foco no tríceps'],
      },
      {
        id: 'ex_push_b_06',
        name: 'Tríceps Francês',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Skull crusher',
        description: 'Deitado com barra EZ ou halteres. Desça flexionando os cotovelos até a testa. Estenda completamente.',
        tips: ['Cotovelos apontados para o teto', 'Amplitude completa para máximo alongamento'],
      },
    ],
  },
  friday: {
    id: 'friday',
    type: 'Pull B',
    label: 'Sexta-feira',
    focus: 'Costas 2',
    color: '#14B8A6',
    emoji: '🎯',
    exercises: [
      {
        id: 'ex_pull_b_01',
        name: 'Remada Unilateral com Halter',
        muscles: ['Latíssimo', 'Rombóide', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 10,
        repsMax: 10,
        intensity: 'Força',
        restSeconds: 75,
        wgerName: 'One arm dumbbell row',
        description: 'Apoie um joelho e mão no banco. Puxe o halter em direção ao quadril retraindo a escápula. Controle a descida completa.',
        tips: ['Não rotacione o tronco durante a puxada', 'Cotovelada para trás e para cima'],
      },
      {
        id: 'ex_pull_b_02',
        wgerId: 103,
        name: 'Remada Baixa na Polia',
        muscles: ['Costas Média', 'Bíceps', 'Rombóide'],
        primaryMuscle: 'Costas',
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Seated row',
        description: 'Sentado na polia baixa. Puxe a pegada até o abdômen retraindo as escápulas. Não arredonde as costas.',
        tips: ['Tronco ereto durante todo o movimento', 'Cotovelos passam pelo lado do corpo'],
      },
      {
        id: 'ex_pull_b_03',
        wgerId: 102,
        name: 'Puxada Aberta na Polia',
        muscles: ['Latíssimo', 'Redondo Maior'],
        primaryMuscle: 'Costas',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Wide-grip lat pulldown',
        description: 'Pegada pronada bem aberta. Puxe até o queixo com os cotovelos apontando para o chão.',
        tips: ['Abra o peito na contração', 'Não incline excessivamente para trás'],
      },
      {
        id: 'ex_pull_b_04',
        name: 'Rosca Concentrada',
        muscles: ['Bíceps'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 12,
        repsMax: 12,
        intensity: 'Hipertrofia',
        restSeconds: 60,
        wgerName: 'Concentration curl',
        description: 'Sentado com o cotovelo apoiado na parte interna da coxa. Flexione completamente até a contração máxima.',
        tips: ['Movimento lento e deliberado', 'Squeeze no topo por 1 segundo'],
      },
      {
        id: 'ex_pull_b_05',
        wgerId: 84,
        name: 'Rosca 21',
        muscles: ['Bíceps'],
        primaryMuscle: 'Bíceps',
        sets: 3,
        repsMin: 21,
        repsMax: 21,
        intensity: 'Resistência',
        restSeconds: 75,
        wgerName: 'Barbell curl',
        description: '7 reps da parte baixa (0° a 90°), 7 da parte alta (90° a 180°), 7 completas. Sensação de queimação total!',
        tips: ['Use carga moderada — a técnica é exigente', 'Foco na contração em cada faixa'],
      },
      {
        id: 'ex_pull_b_06',
        name: 'Encolhimento com Halteres',
        muscles: ['Trapézio'],
        primaryMuscle: 'Trapézio',
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        intensity: 'Resistência',
        restSeconds: 45,
        wgerName: 'Dumbbell shrug',
        description: 'Em pé com halteres ao lado do corpo. Eleve os ombros em direção às orelhas. Segure 2s no topo.',
        tips: ['Amplitude total — desça completamente', 'Não role os ombros para frente'],
      },
    ],
  },
  saturday: { id: 'saturday', type: 'Rest', label: 'Sábado', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
  sunday: { id: 'sunday', type: 'Rest', label: 'Domingo', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
}

// ── Plano feminino (foco inferior) ──────────────────────────────────────────
export const FEMALE_WORKOUT_PLAN = {
  monday: {
    id: 'monday',
    type: 'Inferior A',
    label: 'Segunda-feira',
    focus: 'Quadríceps + Glúteo',
    color: '#EC4899',
    emoji: '🍑',
    exercises: [
      {
        id: 'ex_f_lower_a_01',
        wgerId: 8,
        name: 'Agachamento Livre',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Quadríceps',
        sets: 4, repsMin: 8, repsMax: 10, intensity: 'Força', restSeconds: 90,
        wgerName: 'Squat',
        description: 'Barra nos trapézios, pés na largura dos ombros. Desça com o quadril para trás até as coxas paralelas. Empurre o chão na subida.',
        tips: ['Joelhos seguem a direção dos dedos dos pés', 'Peito alto durante todo o movimento', 'Desça controlado e suba explosivo'],
      },
      {
        id: 'ex_f_lower_a_02',
        wgerId: 45,
        name: 'Leg Press 45°',
        muscles: ['Quadríceps', 'Glúteos'],
        primaryMuscle: 'Quadríceps',
        sets: 4, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 75,
        wgerName: 'Leg press',
        description: 'Pés um pouco mais altos na plataforma para recrutar mais glúteo. Desça controlando até 90° e empurre sem travar os joelhos.',
        tips: ['Pés mais altos = mais glúteo e posterior', 'Não deixe os glúteos saírem do banco'],
      },
      {
        id: 'ex_f_lower_a_03',
        name: 'Hip Thrust com Barra',
        muscles: ['Glúteos', 'Posterior', 'Core'],
        primaryMuscle: 'Glúteos',
        sets: 4, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 75,
        wgerName: 'Hip thrust',
        description: 'Apoie os ombros num banco. Barra com amortecedor sobre o quadril. Eleve o quadril até a extensão completa contraindo ao máximo os glúteos.',
        tips: ['Queixo para o peito no topo', 'Pés a 90° dos joelhos', 'Segure 1s no topo com máxima contração'],
      },
      {
        id: 'ex_f_lower_a_04',
        name: 'Cadeira Extensora',
        muscles: ['Quadríceps'],
        primaryMuscle: 'Quadríceps',
        sets: 3, repsMin: 12, repsMax: 15, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Leg extension',
        description: 'Na cadeira extensora, estenda completamente os joelhos pausando 1 segundo no topo.',
        tips: ['Pause 1s na extensão completa', 'Controle a fase excêntrica'],
      },
      {
        id: 'ex_f_lower_a_05',
        name: 'Abdução de Quadril na Máquina',
        muscles: ['Abdutores', 'Glúteo Médio'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 15, repsMax: 20, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Hip abduction',
        description: 'Na máquina abdutora. Afaste as pernas contra a resistência contraindo o glúteo médio.',
        tips: ['Incline levemente o tronco para frente para recrutar mais glúteo', 'Movimento controlado, não use impulso'],
      },
      {
        id: 'ex_f_lower_a_06',
        name: 'Panturrilha em Pé na Máquina',
        muscles: ['Panturrilha', 'Sóleo'],
        primaryMuscle: 'Panturrilha',
        sets: 3, repsMin: 15, repsMax: 20, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Standing calf raise',
        description: 'Eleve completamente na ponta dos pés, segure 1s, desça abaixo da plataforma.',
        tips: ['Amplitude completa para máximo recrutamento', 'Não use impulso'],
      },
    ],
  },
  tuesday: {
    id: 'tuesday',
    type: 'Superiores A',
    label: 'Terça-feira',
    focus: 'Peito + Costas + Ombro',
    color: '#818CF8',
    emoji: '💪',
    exercises: [
      {
        id: 'ex_f_upper_a_01',
        name: 'Supino com Halteres',
        muscles: ['Peito', 'Tríceps', 'Ombro'],
        primaryMuscle: 'Peito',
        sets: 3, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Dumbbell Bench Press',
        description: 'Deitada no banco com halteres alinhados com o peito. Desça controlando até os cotovelos ficarem abaixo do banco e empurre.',
        tips: ['Retrate as escápulas antes de começar', 'Controle a fase excêntrica em 2-3s'],
      },
      {
        id: 'ex_f_upper_a_02',
        name: 'Remada Curvada com Barra',
        muscles: ['Costas', 'Latíssimo', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 3, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Barbell Row',
        description: 'Tronco a 45° com a barra. Puxe para o umbigo retraindo as escápulas. Cotovelos próximos ao corpo.',
        tips: ['Não arredonde a lombar', 'Puxe com as escápulas, não apenas com os braços'],
      },
      {
        id: 'ex_f_upper_a_03',
        wgerId: 102,
        name: 'Pulldown na Polia',
        muscles: ['Latíssimo', 'Bíceps', 'Costas'],
        primaryMuscle: 'Costas',
        sets: 3, repsMin: 12, repsMax: 15, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Lat pulldown',
        description: 'Incline levemente o tronco. Puxe a barra até o queixo com os cotovelos apontando para o chão.',
        tips: ['Puxe com os cotovelos, não com as mãos', 'Abra o peito na contração'],
      },
      {
        id: 'ex_f_upper_a_04',
        wgerId: 72,
        name: 'Desenvolvimento com Halteres',
        muscles: ['Ombro', 'Tríceps'],
        primaryMuscle: 'Ombro',
        sets: 3, repsMin: 12, repsMax: 15, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Dumbbell Shoulder Press',
        description: 'Sentada com halteres na altura dos ombros. Empurre acima da cabeça sem arquear as costas.',
        tips: ['Abdômen contraído para estabilidade', 'Não arqueie a lombar'],
      },
      {
        id: 'ex_f_upper_a_05',
        name: 'Rosca Alternada com Halteres',
        muscles: ['Bíceps', 'Braquial'],
        primaryMuscle: 'Bíceps',
        sets: 3, repsMin: 12, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 45,
        wgerName: 'Alternating Dumbbell Curl',
        description: 'Flexione cada braço alternadamente girando o punho no topo para supinar completamente.',
        tips: ['Cotovelos fixos ao lado do corpo', 'Supine o punho no topo para máxima contração'],
      },
      {
        id: 'ex_f_upper_a_06',
        wgerId: 63,
        name: 'Tríceps Corda (Pulley)',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3, repsMin: 15, repsMax: 15, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Triceps pushdown',
        description: 'Polia alta com corda. Puxe para baixo abrindo as pontas ao final da extensão.',
        tips: ['Cotovelos fixos ao lado do corpo', 'Contração total no fundo'],
      },
    ],
  },
  wednesday: {
    id: 'wednesday',
    type: 'Inferior B',
    label: 'Quarta-feira',
    focus: 'Glúteo + Posterior',
    color: '#F59E0B',
    emoji: '🔥',
    exercises: [
      {
        id: 'ex_f_lower_b_01',
        name: 'Hip Thrust com Barra',
        muscles: ['Glúteos', 'Posterior', 'Core'],
        primaryMuscle: 'Glúteos',
        sets: 4, repsMin: 8, repsMax: 10, intensity: 'Força', restSeconds: 90,
        wgerName: 'Hip thrust',
        description: 'Ombros apoiados no banco, barra com amortecedor sobre o quadril. Eleve com máxima contração dos glúteos.',
        tips: ['Queixo para o peito no topo', 'Pés a 90° dos joelhos', 'Contração máxima no topo por 1s'],
      },
      {
        id: 'ex_f_lower_b_02',
        name: 'Stiff com Halteres (RDL)',
        muscles: ['Posterior', 'Glúteos', 'Lombar'],
        primaryMuscle: 'Posterior',
        sets: 4, repsMin: 10, repsMax: 12, intensity: 'Força', restSeconds: 75,
        wgerName: 'Romanian deadlift',
        description: 'Em pé com halteres. Incline o tronco mantendo costas neutras, descendo até sentir o alongamento nos posteriores.',
        tips: ['Costas retas durante todo o movimento', 'Halteres deslizam pelas pernas', 'Sinta o alongamento antes de subir'],
      },
      {
        id: 'ex_f_lower_b_03',
        name: 'Mesa Flexora',
        muscles: ['Posterior', 'Panturrilha'],
        primaryMuscle: 'Posterior',
        sets: 3, repsMin: 12, repsMax: 15, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Leg curl',
        description: 'Deitada na mesa flexora. Flexione totalmente as pernas e controle a descida.',
        tips: ['Não use impulso', 'Controle total na fase excêntrica (3-4s na descida)'],
      },
      {
        id: 'ex_f_lower_b_04',
        wgerId: 80,
        name: 'Avanço com Halteres',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 10, repsMax: 10, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Lunge',
        description: 'Em pé com halteres. Avance um passo largo. O joelho traseiro quase toca o chão. Empurre de volta.',
        tips: ['Tronco ereto', 'Joelho da frente não ultrapassa a ponta do pé'],
      },
      {
        id: 'ex_f_lower_b_05',
        name: 'Cadeira Abdutora',
        muscles: ['Abdutores', 'Glúteo Médio'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 15, repsMax: 20, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Hip abduction machine',
        description: 'Na máquina abdutora. Afaste as pernas contraindo o glúteo médio. Pause no ponto de maior abdução.',
        tips: ['Incline levemente o tronco para frente', 'Pause no ponto de maior abdução por 1s'],
      },
      {
        id: 'ex_f_lower_b_06',
        name: 'Elevação Pélvica (Glute Bridge)',
        muscles: ['Glúteos', 'Core'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 15, repsMax: 20, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Glute bridge',
        description: 'Deitada de costas com joelhos flexionados. Eleve o quadril contraindo os glúteos. Pode adicionar um peso no quadril.',
        tips: ['Pause 2s no topo', 'Não arqueie a lombar em excesso', 'Progresso: adicione um halter ou anilha no quadril'],
      },
    ],
  },
  thursday: {
    id: 'thursday',
    type: 'Superiores B',
    label: 'Quinta-feira',
    focus: 'Costas + Ombro + Braços',
    color: '#C8FF00',
    emoji: '⚡',
    exercises: [
      {
        id: 'ex_f_upper_b_01',
        name: 'Supino Inclinado com Halteres',
        muscles: ['Peito Superior', 'Ombro', 'Tríceps'],
        primaryMuscle: 'Peito Superior',
        sets: 3, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Incline Dumbbell Bench Press',
        description: 'Banco a 30–45°. Desça controlando e empurre até a extensão quase completa.',
        tips: ['Não deixe os cotovelos caírem abaixo do banco', 'Foco na contração no topo'],
      },
      {
        id: 'ex_f_upper_b_02',
        name: 'Remada Unilateral com Halter',
        muscles: ['Latíssimo', 'Rombóide', 'Bíceps'],
        primaryMuscle: 'Costas',
        sets: 3, repsMin: 10, repsMax: 12, intensity: 'Força', restSeconds: 60,
        wgerName: 'One arm dumbbell row',
        description: 'Apoie joelho e mão no banco. Puxe o halter em direção ao quadril retraindo a escápula.',
        tips: ['Não rotacione o tronco', 'Cotovelada para trás e para cima'],
      },
      {
        id: 'ex_f_upper_b_03',
        wgerId: 102,
        name: 'Puxada Aberta na Polia',
        muscles: ['Latíssimo', 'Redondo Maior'],
        primaryMuscle: 'Costas',
        sets: 3, repsMin: 12, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Wide-grip lat pulldown',
        description: 'Pegada pronada bem aberta. Puxe até o queixo com os cotovelos apontando para o chão.',
        tips: ['Abra o peito na contração', 'Não incline excessivamente para trás'],
      },
      {
        id: 'ex_f_upper_b_04',
        wgerId: 112,
        name: 'Elevação Lateral com Halteres',
        muscles: ['Ombro Lateral'],
        primaryMuscle: 'Ombro Lateral',
        sets: 3, repsMin: 15, repsMax: 15, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Lateral raise',
        description: 'Eleve lateralmente com leve inclinação para frente até a linha dos ombros.',
        tips: ['Cotovelos levemente flexionados', 'Evite usar impulso do tronco'],
      },
      {
        id: 'ex_f_upper_b_05',
        wgerId: 118,
        name: 'Rosca Martelo',
        muscles: ['Bíceps', 'Braquiorradial'],
        primaryMuscle: 'Bíceps',
        sets: 3, repsMin: 12, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 45,
        wgerName: 'Hammer curl',
        description: 'Pegada neutra com halteres. Flexione alternado ou simultaneamente até os ombros.',
        tips: ['Polegares sempre apontando para cima', 'Movimento lento na descida'],
      },
      {
        id: 'ex_f_upper_b_06',
        name: 'Tríceps Francês com Halter',
        muscles: ['Tríceps'],
        primaryMuscle: 'Tríceps',
        sets: 3, repsMin: 12, repsMax: 15, intensity: 'Hipertrofia', restSeconds: 45,
        wgerName: 'Skull crusher',
        description: 'Deitada com haltere seguro com ambas as mãos acima da cabeça. Flexione os cotovelos trazendo o peso à testa.',
        tips: ['Cotovelos apontados para o teto', 'Amplitude completa para máximo alongamento do tríceps'],
      },
    ],
  },
  friday: {
    id: 'friday',
    type: 'Inferior C',
    label: 'Sexta-feira',
    focus: 'Glúteo + Quadríceps',
    color: '#14B8A6',
    emoji: '🎯',
    exercises: [
      {
        id: 'ex_f_lower_c_01',
        name: 'Agachamento Sumô com Haltere',
        muscles: ['Glúteos', 'Quadríceps', 'Adutores'],
        primaryMuscle: 'Glúteos',
        sets: 4, repsMin: 10, repsMax: 12, intensity: 'Força', restSeconds: 90,
        wgerName: 'Sumo squat',
        description: 'Pés afastados com pés apontando para fora. Segure um halter verticalmente entre as pernas. Desça com o peito alto.',
        tips: ['Joelhos seguem a direção dos dedos dos pés', 'Peito alto e costas retas', 'Ative o glúteo na subida'],
      },
      {
        id: 'ex_f_lower_c_02',
        name: 'Hip Thrust com Barra',
        muscles: ['Glúteos', 'Posterior', 'Core'],
        primaryMuscle: 'Glúteos',
        sets: 4, repsMin: 10, repsMax: 12, intensity: 'Hipertrofia', restSeconds: 75,
        wgerName: 'Hip thrust',
        description: 'Ombros apoiados no banco. Eleve o quadril até a extensão completa contraindo os glúteos.',
        tips: ['Queixo para o peito no topo', 'Squeeze máximo por 1s', 'Pés a 90° dos joelhos'],
      },
      {
        id: 'ex_f_lower_c_03',
        name: 'Avanço Reverso com Halteres',
        muscles: ['Quadríceps', 'Glúteos', 'Posterior'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 10, repsMax: 10, intensity: 'Hipertrofia', restSeconds: 60,
        wgerName: 'Reverse lunge',
        description: 'Em pé com halteres. Recue uma perna, abaixe até o joelho quase tocar o chão. Empurre pela perna da frente para voltar.',
        tips: ['Tronco ereto', 'Controla melhor o equilíbrio que o avanço normal', 'Foco na perna da frente ao subir'],
      },
      {
        id: 'ex_f_lower_c_04',
        name: 'Cadeira Extensora',
        muscles: ['Quadríceps'],
        primaryMuscle: 'Quadríceps',
        sets: 3, repsMin: 15, repsMax: 15, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Leg extension',
        description: 'Estenda completamente os joelhos e controle a fase excêntrica.',
        tips: ['Pause 1s na extensão completa', 'Foco na contração do quadríceps'],
      },
      {
        id: 'ex_f_lower_c_05',
        name: 'Abdução de Quadril em Pé (Cabo)',
        muscles: ['Abdutores', 'Glúteo Médio'],
        primaryMuscle: 'Glúteos',
        sets: 3, repsMin: 15, repsMax: 15, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Cable hip abduction',
        description: 'De pé na polia baixa com tornozeleira. Afaste a perna lateralmente contraindo o glúteo médio.',
        tips: ['Mantenha o tronco estável', 'Movimento lento e controlado'],
      },
      {
        id: 'ex_f_lower_c_06',
        wgerId: 10,
        name: 'Abdominais',
        muscles: ['Abdômen', 'Core'],
        primaryMuscle: 'Core',
        sets: 3, repsMin: 20, repsMax: 20, intensity: 'Resistência', restSeconds: 45,
        wgerName: 'Crunch',
        description: 'Deitada com joelhos flexionados. Eleve o tronco contraindo o abdômen.',
        tips: ['Respire na subida', 'Não puxe a cabeça com as mãos'],
      },
    ],
  },
  saturday: { id: 'saturday', type: 'Rest', label: 'Sábado', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
  sunday: { id: 'sunday', type: 'Rest', label: 'Domingo', focus: 'Descanso', color: '#555', emoji: '😴', exercises: [] },
}

export function getWorkoutPlan(gender) {
  return gender === 'female' ? FEMALE_WORKOUT_PLAN : WORKOUT_PLAN
}

export const DAY_ORDER = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

export const DAY_LABELS_SHORT = {
  monday: 'Seg',
  tuesday: 'Ter',
  wednesday: 'Qua',
  thursday: 'Qui',
  friday: 'Sex',
  saturday: 'Sáb',
  sunday: 'Dom',
}

export function getTodayKey() {
  const days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
  return days[new Date().getDay()]
}

export function getIntensityColor(intensity) {
  switch (intensity) {
    case 'Força': return '#EF4444'
    case 'Hipertrofia': return '#C8FF00'
    case 'Resistência': return '#F59E0B'
    default: return '#888'
  }
}

export function formatReps(min, max) {
  if (min === max) return `${min}`
  return `${min}–${max}`
}
